'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
// Actions
var ADD_ITEM = exports.ADD_ITEM = 'ADD_ITEM';
var REMOVE_ITEM = exports.REMOVE_ITEM = 'REMOVE_ITEM';
var SET_ITEM = exports.SET_ITEM = 'SET_ITEM';
var RESET_ITEM = exports.RESET_ITEM = 'RESET_ITEM';
var MOVE_ITEM = exports.MOVE_ITEM = 'MOVE_ITEM';

// Types
var SURVEY = exports.SURVEY = 'SURVEY';
var PAGE = exports.PAGE = 'PAGE';
var QUESTION_TEXT = exports.QUESTION_TEXT = 'QUESTION_TEXT';
var QUESTION_TEXT_AREA = exports.QUESTION_TEXT_AREA = 'QUESTION_TEXT_AREA';
var QUESTION_DATE = exports.QUESTION_DATE = 'QUESTION_DATE';
var QUESTION_DISCRETE_SCALE = exports.QUESTION_DISCRETE_SCALE = 'QUESTION_DISCRETE_SCALE';
var QUESTION_NUMERICAL_SCALE = exports.QUESTION_NUMERICAL_SCALE = 'QUESTION_NUMERICAL_SCALE';
var QUESTION_CHOICES = exports.QUESTION_CHOICES = 'QUESTION_CHOICES';
var QUESTION_MATRIX = exports.QUESTION_MATRIX = 'QUESTION_MATRIX';
var QUESTION_IMAGE = exports.QUESTION_IMAGE = 'QUESTION_IMAGE';
var QUESTION_RANK = exports.QUESTION_RANK = 'QUESTION_RANK';