'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var QUESTION_SWITCH = exports.QUESTION_SWITCH = 'QUESTION_SWITCH';
var QUESTION_TEXT = exports.QUESTION_TEXT = 'QUESTION_TEXT';
var QUESTION_TEXT_AREA = exports.QUESTION_TEXT_AREA = 'QUESTION_TEXT_AREA';
var QUESTION_RATE = exports.QUESTION_RATE = 'QUESTION_RATE';
var QUESTION_DATE = exports.QUESTION_DATE = 'QUESTION_DATE';
var QUESTION_DISCRETE_SCALE = exports.QUESTION_DISCRETE_SCALE = 'QUESTION_DISCRETE_SCALE';
var QUESTION_NUMERICAL_SCALE = exports.QUESTION_NUMERICAL_SCALE = 'QUESTION_NUMERICAL_SCALE';
var QUESTION_CHOICES = exports.QUESTION_CHOICES = 'QUESTION_CHOICES';
var QUESTION_MATRIX = exports.QUESTION_MATRIX = 'QUESTION_MATRIX';
var QUESTION_IMAGE = exports.QUESTION_IMAGE = 'QUESTION_IMAGE';
var QUESTION_RANK = exports.QUESTION_RANK = 'QUESTION_RANK';
var QUESTION_CASCADE = exports.QUESTION_CASCADE = 'QUESTION_CASCADE';

var ADD_QUESTION = exports.ADD_QUESTION = 'ADD_QUESTION';
var REMOVE_QUESTION = exports.REMOVE_QUESTION = 'REMOVE_QUESTION';
var SET_QUESTION = exports.SET_QUESTION = 'SET_QUESTION';
var MOVE_QUESTION = exports.MOVE_QUESTION = 'MOVE_QUESTION';